# Generated by Django 6.0.3 on 2026-06-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterion",
            name="priority",
            field=models.CharField(
                choices=[("Alta", "High"), ("Media", "Medium"), ("Baja", "Low")],
                default="Baja",
                max_length=20,
            ),
        ),
    ]
