# Generated by Django 6.0.3 on 2026-08-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_criterion_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedevidence',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedevidence',
            name='file_path',
            field=models.FileField(upload_to='evidences/'),
        ),
    ]
