# Generated by Django 6.0.3 on 2026-08-18 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_uploadedevidence_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedevidence',
            name='required_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_instances', to='rest_api.requiredevidence'),
        ),
        migrations.AlterField(
            model_name='uploadedevidence',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to='rest_api.task'),
        ),
    ]
