# Generated by Django 6.0.3 on 2026-08-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_uploadedevidence_required_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requirement_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rest_api.requirementversion'),
        ),
    ]
