from .views import (
    CertificationModelViewSet as CertificationModelViewSet,
    PeriodViewSet as PeriodViewSet,
    CriterionViewSet as CriterionViewSet,
    RequirementViewSet as RequirementViewSet,
    RequirementVersionViewSet as RequirementVersionViewSet,
    BranchViewSet as BranchViewSet,
    DepartmentViewSet as DepartmentViewSet,
    WorkGroupViewSet as WorkGroupViewSet,
    WorkGroupMemberViewSet as WorkGroupMemberViewSet,
    TaskViewSet as TaskViewSet,
    RequiredEvidenceViewSet as RequiredEvidenceViewSet,
    UploadedEvidenceViewSet as UploadedEvidenceViewSet,
    FeedbackViewSet as FeedbackViewSet,
    UserViewSet as UserViewSet,
    LoginView as LoginView,
)
